-- Live schema contract for SHELLHACKS_DB.STORY_MODE.
-- This file records the definitions used by the backend and team pipelines.
-- Changes to existing objects go in snowflake/migrations/ and are reflected here.

-- Daily prices. The single source of price data; PRICE_HISTORY is a view over it.
CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.PRICES (
  TICKER VARCHAR(16) NOT NULL, DATE DATE NOT NULL, OPEN NUMBER(18,4),
  HIGH NUMBER(18,4), LOW NUMBER(18,4), CLOSE NUMBER(18,4) NOT NULL,
  VOLUME NUMBER(38,0), SOURCE VARCHAR(100),
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (TICKER, DATE)
);

-- Closing price with the day's change, calculated from PRICES (migration 001).
CREATE OR REPLACE VIEW SHELLHACKS_DB.STORY_MODE.PRICE_HISTORY AS
SELECT
    TICKER AS SYMBOL,
    DATE   AS TRADE_DATE,
    CLOSE  AS CLOSE_PRICE,
    ROUND((CLOSE / LAG(CLOSE) OVER (PARTITION BY TICKER ORDER BY DATE) - 1) * 100, 4)
           AS DAILY_RETURN_PCT,
    CASE
        WHEN CLOSE > LAG(CLOSE) OVER (PARTITION BY TICKER ORDER BY DATE) THEN 'up'
        WHEN CLOSE < LAG(CLOSE) OVER (PARTITION BY TICKER ORDER BY DATE) THEN 'down'
        WHEN LAG(CLOSE) OVER (PARTITION BY TICKER ORDER BY DATE) IS NULL THEN NULL
        ELSE 'flat'
    END    AS DIRECTION,
    SOURCE AS DATA_SOURCE,
    INGESTED_AT
FROM SHELLHACKS_DB.STORY_MODE.PRICES;

-- Story Mode (migration 001). A story is three parts: STORIES (one per
-- company), STORY_EVENTS (one per labeled move), STORY_EVIDENCE (one per
-- citable fact). An event cites evidence through CITATION_IDS; join with
-- LATERAL FLATTEN(input => CITATION_IDS). Rebuilding a company's story deletes
-- its rows by SYMBOL and inserts fresh ones.
CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.STORIES (
  STORY_ID VARCHAR NOT NULL, SYMBOL VARCHAR(16) NOT NULL, COMPANY_NAME VARCHAR,
  GENERATED_AT TIMESTAMP_TZ, ARC VARCHAR, ARC_CITATION_IDS ARRAY, WARNINGS ARRAY,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (STORY_ID)
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.STORY_EVENTS (
  EVENT_ID VARCHAR NOT NULL, STORY_ID VARCHAR NOT NULL, SYMBOL VARCHAR(16) NOT NULL,
  EVENT_DATE DATE NOT NULL, EVENT_TYPE VARCHAR(50) NOT NULL DEFAULT 'price_move',
  PRICE_MOVE_PCT NUMBER(10,4), CLOSE_PRICE NUMBER(18,4), DIRECTION VARCHAR(4),
  HEADLINE VARCHAR NOT NULL, SUMMARY VARCHAR NOT NULL, CONFIDENCE VARCHAR(6),
  CITATION_IDS ARRAY, INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (EVENT_ID)
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.STORY_EVIDENCE (
  EVIDENCE_ID VARCHAR NOT NULL, STORY_ID VARCHAR NOT NULL, SYMBOL VARCHAR(16) NOT NULL,
  KIND VARCHAR(20), TITLE VARCHAR, DETAIL VARCHAR, SOURCE VARCHAR, URL VARCHAR,
  OCCURRED_ON DATE, NUMBERS VARIANT,
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (EVIDENCE_ID)
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.NEWS (
  NEWS_ID VARCHAR(100) NOT NULL, TICKER VARCHAR(16) NOT NULL,
  PUBLISHED_AT TIMESTAMP_TZ NOT NULL, HEADLINE VARCHAR NOT NULL, SUMMARY VARCHAR,
  URL VARCHAR, SOURCE VARCHAR(100), CATEGORY VARCHAR(100),
  INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), PRIMARY KEY (NEWS_ID)
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.FUNDAMENTALS (
  TICKER VARCHAR(16) NOT NULL, AS_OF_DATE DATE NOT NULL,
  REVENUE_GROWTH NUMBER(10,4), PROFIT_MARGIN NUMBER(10,4),
  DEBT_TO_EQUITY NUMBER(12,4), VOLATILITY NUMBER(10,4),
  MARKET_CAP NUMBER(24,2), SECTOR VARCHAR(100), INDUSTRY VARCHAR(200),
  SOURCE VARCHAR(100), INGESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (TICKER, AS_OF_DATE)
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.GRAPH_EDGES (
  FROM_ID VARCHAR, FROM_NAME VARCHAR, FROM_TYPE VARCHAR, RELATIONSHIP VARCHAR,
  TO_ID VARCHAR, TO_NAME VARCHAR, TO_TYPE VARCHAR, KIND VARCHAR, DETAIL VARCHAR,
  SOURCE VARCHAR, REPORTED_BY VARCHAR, CONFIDENCE VARCHAR, EVIDENCE VARCHAR,
  FILING_URL VARCHAR, NOTE VARCHAR
);

CREATE TABLE IF NOT EXISTS SHELLHACKS_DB.STORY_MODE.GRAPH_COMPANIES (
  TICKER VARCHAR, NAME VARCHAR, IN_UNIVERSE BOOLEAN, CIK NUMBER,
  SECTOR VARCHAR, HQ_COUNTRY VARCHAR
);
