-- Run once in Snowsight as ACCOUNTADMIN.
-- This grants the app only the permissions it needs; do not use ACCOUNTADMIN
-- in the backend.
--
-- The matching private key stays in the deployment secret store or in
-- backend/keys/ locally. Never commit it, email it, or paste it into chat.

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS SHELLHACKS_APP_ROLE;

CREATE USER IF NOT EXISTS SHELLHACKS_APP
  TYPE = SERVICE
  DEFAULT_ROLE = SHELLHACKS_APP_ROLE
  DEFAULT_WAREHOUSE = SHELLHACKS_WH
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw4TYUVPDrgoieVBZH3vjO/06YvEKilwe0iTX8JQqTd1WpuV6hCAnu9eGsyWOuebVQlvNB3uU06sLhGHT2lc6Zo0UzgfkDXp3wF7OZNmD3Jkavq9kmsWeNJELQmvH0GUDLtANCW6BezU9qE1JS1IPCelclI9RzEGrc+5GsmmzRXxeRryZylyAmqGnIWHWXGIW/OECr/oEyZH8zzetmnN0/szDZvpkJXZBKrDKYDpEX7CkPM9y78Ly2ufXR7kbtJotZBk3lpyHHr1wSSn1g/Z+w17E3JDGzWPNZ6J31Gdku36euSHYwcRrPAvUvtUcNbixBvCSaOUygKwUv/AQEDrOqwIDAQAB';

GRANT ROLE SHELLHACKS_APP_ROLE TO USER SHELLHACKS_APP;

GRANT USAGE ON WAREHOUSE SHELLHACKS_WH TO ROLE SHELLHACKS_APP_ROLE;
GRANT USAGE ON DATABASE SHELLHACKS_DB TO ROLE SHELLHACKS_APP_ROLE;
GRANT USAGE ON SCHEMA SHELLHACKS_DB.STORY_MODE TO ROLE SHELLHACKS_APP_ROLE;

-- The app can read the data and insert incoming data. It can create an
-- internal stage only if the uploader uses staged file uploads.
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SHELLHACKS_DB.STORY_MODE
  TO ROLE SHELLHACKS_APP_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SHELLHACKS_DB.STORY_MODE
  TO ROLE SHELLHACKS_APP_ROLE;
GRANT CREATE STAGE ON SCHEMA SHELLHACKS_DB.STORY_MODE TO ROLE SHELLHACKS_APP_ROLE;
